In [63]:
import pandas as pd

In [64]:
df = pd.read_csv(r"C:\Users\singh\OneDrive\Desktop\NLP\Data\all_kindle_review.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [65]:
df = df[['reviewText', 'rating']]
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [66]:
df.shape

(12000, 2)

In [67]:
## Checking missing Values
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [68]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [69]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [70]:
## Preprocessing and Cleaning

# Postitve Review --> 1 and Negative review ---> 0
df['rating'] = df['rating'].apply(lambda x : 0 if x < 3 else 1)

In [71]:
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [72]:
df['rating'].unique()

array([1, 0])

In [73]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [74]:
## Lower all the Cases
df['reviewText'] = df['reviewText'].str.lower()

In [75]:
df.head()

                                          reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [76]:
import re

def remove_special_characters(text):
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text

df['reviewText'] = df['reviewText'].apply(remove_special_characters)

In [77]:
df.sample(10)

                                              reviewText  rating
5992   essentially it has the same ending as in ink e...       0
5735   these mysteries are mundane examples of how a ...       1
8638   just a small book of sex and nothing else i do...       0
2635   i persevered despite the grammar and spelling ...       1
6838   i wish someone would have warned meshane is wo...       0
11842  did not like this book at all  the bondage is ...       0
1920   this book was not a blockbuster but i enjoyed ...       1
5866   belinda belle campbell has had more than her f...       1
1101   i love this book im not even halfway thru it a...       1
6028   i enjoyed this collection of short stories  i ...       0

In [78]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\singh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [79]:
## Removing Stopwords
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in stop_words]
    return " ".join(filtered_words)

df['reviewText'] = df['reviewText'].apply(remove_stopwords)

In [80]:
df.sample(10)

                                              reviewText  rating
7070   every sex scene taking anallyand im prude seem...       0
11797  book spans genres gay erotic cop paranormal ye...       1
1860   book good enough romance goes details surround...       1
1586   book makes much sense practices easy follow iv...       1
8614   guess far short story go good short stories al...       1
6153   sister asked opportunity naughty guy protect a...       0
7930   agree another reviewer arent norse mythology b...       1
11646  okay read gave book one stars based engages em...       0
1336   much back forth enjoyed could put back kept sa...       1
10139  damaged goods second book ive read reviewed ta...       1

In [81]:
## Removing URL's

def remove_urls(text):
    url_pattern = r'https?://\S+|www\.\S+'
    return re.sub(url_pattern, '', text)

df['reviewText'] = df['reviewText'].apply(remove_urls)

In [82]:
df.sample(10)

                                              reviewText  rating
7244   yet disappointed ms andrews enjoyed world sist...       1
2127   like good templar story well next person one i...       0
7912   two connected novellas two sisters love storie...       1
4722   love good romance one definitely fit bill char...       1
303    nice collection well known works lesser known ...       1
3682   found book far fetched wasnt funny prefer read...       0
6158   rhonda amazing writing characters making feel ...       1
10360  tried book free basis suite style reading wort...       0
10306  werewolves one keith abbys story one told stor...       1
1508   problem story straight bateleanor submissive y...       0

In [83]:
## Removing HTML Tags
from bs4 import BeautifulSoup

def remove_html_tags(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

df['reviewText'] = df['reviewText'].apply(remove_html_tags)

In [84]:
df.sample(10)

                                              reviewText  rating
9100   good sequel prima carolyn faulkner first intro...       1
3762   author suffered sexual abuse child grew learni...       1
9887   talk point life true love easy find three favo...       1
4618   found story entertaining much short story open...       1
4431   another addition series nice short read even t...       1
5116   really fun really quick smutty read vampires n...       1
11751  1 started good details exciting though going f...       1
3244   enjoyed story even though short one perhaps im...       1
8870   see review old kindle app rated one star uppin...       1
4255   ok 2nd book favorite trilogy one good little t...       1

In [85]:
## Remove Additional Whitespaces
import re
def remove_extra_whitespace(text):
    text = re.sub(r'\s+', ' ', text)   
    return text.strip()                

df['reviewText'] = df['reviewText'].apply(remove_extra_whitespace)

In [86]:
df.sample(10)

                                              reviewText  rating
165      part series read loved whole series also kindle       1
669    female character annoyed didnt finish worth fi...       0
1866   e poe came h p lovecraft world written horror ...       1
11188  reader wants lots sex short book thing looking...       0
4220   basically title three star reviewer sums perfe...       0
11383  great book insight life first generation tanks...       1
6858   another collection short stories like first an...       0
923    dont normally read short storiesnovellas find ...       1
2139   wsj kindle overpriced customer service gone co...       0
2194   eight years ago charlie met summer affair ricc...       1

In [87]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [88]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [89]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

In [90]:
df.head()

                                          reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [91]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],
                                              test_size=0.20)

In [92]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [93]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [94]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tfidf,y_train)

In [95]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [96]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [97]:
y_pred_tfidf = nb_model_bow.predict(X_test_tfidf)

In [98]:
confusion_matrix(y_test,y_pred_bow)

array([[545, 285],
       [705, 865]])

In [99]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.5875

In [100]:
confusion_matrix(y_test,y_pred_tfidf)

array([[534, 296],
       [699, 871]])

In [101]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.5854166666666667