In [14]:
import pandas as pd

In [15]:
import os
ROOT_DIR = os.getcwd()

DATA_PATH = os.path.join(ROOT_DIR,  "Data", "IMDB Dataset.csv")

In [16]:
df = pd.read_csv(DATA_PATH)
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## Lowercasing

In [17]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [18]:
df.shape

(50000, 2)

In [19]:
df['review'] = df['review'].str.lower()

In [20]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

## Removing HTML Tags

In [21]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [22]:
df['review'] = df['review'].apply(remove_html_tags)

In [23]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

## Removing URL's

In [24]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [25]:
## Example
text3 = 'Google Search Here www.google.com'
remove_url(text3)

'Google Search Here '

## Removing Punctuation

In [28]:
import string, time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [29]:
exclude = string.punctuation
def remove_punc(text):
    for char in exclude:
        text = text.replace(char, "")
    return text

In [35]:
TEXT = "string. With. Punctuation?"
start = time.time()
print(remove_punc(TEXT))
time1 = time.time() - start
print(time1)

string With Punctuation
0.0007483959197998047

In [31]:
def remove_punc1(text):
    return text.translate(str.maketrans("", '', exclude))

In [34]:
start = time.time()
remove_punc1(TEXT)
time2 = time.time() - start
print(time2)

0.00011706352233886719

In [33]:
time1 / time2

1.9794007490636705